apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: hpa-demo
  labels:
    app: load-generator
spec:
  replicas: 0
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: busybox
          image: busybox:1.36.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting load against cpu-demo service...";
              while true; do
                wget -q -O- http://cpu-demo >/dev/null 2>&1
              done
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
