apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-demo-keyvault-csi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                        # Set to true for using managed identity
    userAssignedIdentityID: "7904a528-77ee-4eb9-a9f6-a34ef3f35c92"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "upskillingkv3455"                 # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: ExampleSecret            # keyvault secret name
          objectType: secret
    tenantId: 1b629ffc-9c1b-447f-bf6b-de0098bf4d67                 # The tenant ID of the key vault