apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: statefulset-demo
  labels:
    app: toolbox
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.6.0
      command: ["sh", "-c", "sleep 365d"]
  restartPolicy: Always
