apiVersion: v1
kind: Service
metadata:
  name: production-svc
  labels:
    color: green
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    target: green-deploy
  type: LoadBalancer
