apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deploy
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fe-deploy
  template:
    metadata:
      labels:
        app: fe-deploy
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: fe-deploy
          image: nginx:alpine
          resources:
            requests:
              cpu: 1