apiVersion: karpenter.azure.com/v1beta1
kind: AKSNodeClass
name: default
spec:
  imageFamily: Ubuntu2204
  osDiskSizeGB: 128
  images:
  - id: /subscriptions/109a5e88-712a-48ae-9078-9ca8b3c81345/resourceGroups/AKS-Ubuntu/providers/Microsoft.Compute/galleries/AKSUbuntu/images/2204gen2containerd/versions/202509.23.0
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.azure.com/sku-hyperv-generation
      operator: In
      values:
      - "2"
  - id: /subscriptions/109a5e88-712a-48ae-9078-9ca8b3c81345/resourceGroups/AKS-Ubuntu/providers/Microsoft.Compute/galleries/AKSUbuntu/images/2204containerd/versions/202509.23.0
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.azure.com/sku-hyperv-generation
      operator: In
      values:
      - "1"
  - id: /subscriptions/109a5e88-712a-48ae-9078-9ca8b3c81345/resourceGroups/AKS-Ubuntu/providers/Microsoft.Compute/galleries/AKSUbuntu/images/2204gen2arm64containerd/versions/202509.23.0
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.azure.com/sku-hyperv-generation
      operator: In
      values:
      - "2"
  kubernetesVersion: 1.32.7
