apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    project: mysql-test
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 2Gi