apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
data:
  username: dXNlcm5hbWU=   # "username" base64 encoded
  password: cGFzc3dvcmQ=   # "password" base64 encoded
  apiKey: YXBpa2V5MTIzNDU= # "apikey12345" base64 encoded