apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello World</title>
      <link rel="stylesheet" href="styles.css">
    </head>
    <body>
      <h1>Hello, Openshift!</h1>
    </body>
    </html>
  styles.css: |
    body {
      background-color: #f0f0f0;
      text-align: center;
      text-shadow: 2px 2px 4px #aaa;
      font-family: Arial, sans-serif;
    }
    h1 {
      color: #0078d4;
    }