apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: app-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
        environment: dev
    spec:
      containers:
      - image: ghcr.io/marcelloraffaele/hello:under-construction
        name: example-app
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-app
  namespace: app-dev
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: dev.example.local
    http:
      paths:
      - backend:
          service:
            name: example-app
            port:
              number: 8080
        path: /
        pathType: Prefix
