apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: demo-app
          image: nginx:alpine
          resources:
            requests:
              cpu: 8