apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: burstable
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  limits:
    cpu: 16
    memory: 32Gi
  weight: 100
  template:
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"] # arm64
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"] # spot
        - key: karpenter.azure.com/sku-family
          operator: In
          values: [B]
        - key: karpenter.azure.com/sku-cpu
          operator: In
          values: ["2", "4", "8"]
        - key: karpenter.azure.com/sku-version
          operator: Gt
          values: ["2"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["1", "2", "3"]
#---
#apiVersion: karpenter.azure.com/v1alpha2
#kind: AKSNodeClass
#metadata:
#  name: default
#  annotations:
#    kubernetes.io/description: "General purpose AKSNodeClass for running Ubuntu2204 nodes"
#spec:
#  imageFamily: Ubuntu2204