apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello World</title>
      <link rel="stylesheet" href="styles.css">
    </head>
    <body>
      <h1>Hello, Kubernetes!</h1>
    </body>
    </html>
  styles.css: |
    body {
      background-color: #f0f0f0;
      text-align: center;
      text-shadow: 2px 2px 4px #aaa;
      font-family: Arial, sans-serif;
    }
    h1 {
      color: #0078d4;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: html-config
              mountPath: /usr/share/nginx/html/styles.css
              subPath: styles.css
      volumes:
        - name: html-config
          configMap:
            name: hello-html-config